name: Create Upgrade-Pull-Requests
'on':
  schedule:
  - cron: '*/10 * * * *'
  workflow_dispatch: null
jobs:
  upgrade-pullrequests:
    if: ${{ github.repository_owner == 'playground-nils' }}
    uses: gardener/cc-utils/.github/workflows/upgrade-dependencies.yaml@v1
    permissions:
      contents: read
      id-token: write
